# The name of the bundle and title of the window
name: "NES Bundler Demo"

# Optional version of your game, will default to the nes-bundler version if omitted
# NOTE: Must be semver
# version: "1.0.0"

# Short description shown in the executable's metadata
short_description: "A demonstration of NES Bundler in action!"

# Used as the user-data directory namespace alongside `name`
manufacturer: "Darkbits"

# A list of supported NES regions (Pal, Ntsc and Dendy available)
# There will be an option in the settings to switch between regions if there are more than one in this list.
# The first in the list will be the default region, and also the region used for Netplay (since it has to be the same for both players)
supported_nes_regions:
  - Ntsc

# There might be tearing if disabled, there might be more dropped frames if enabled
enable_vsync: false

# Starts the game in fullscreen if true
start_in_fullscreen: false

# Optional vocabulary to change some parts of the UI.
# If you have more needs file an issue or open a PR
vocabulary:
  # The name of the inputs in the key mapping section
  input_buttons:
    up: Up
    down: Down
    left: Left
    right: Right
    select: Select
    start: Start
    b: B
    a: A

# This will be the default settings for the game.
# For all the gory details see the `BuildConfiguration`-struct in the source.
default_settings:
  audio:
    volume: 100 #in %
    latency_micros: 16000 #in μs
  input:
    # Two ids that corresponds to the selected input mapping configuration of P1 and P2. Should only be keyboard mappings as they're guaranteed to be available.
    selected:
      - 00-keyboard-1
      - 00-keyboard-2
    # A list of input mapping configurations. For more key mappings see https://github.com/tedsteen/nes-bundler/blob/master/src/input/keys.rs#L28.
    # To add a gamepad configuration use the kind `Gamepad` and id `01-gamepad-0` for the first gamepad that connects, `01-gamepad-1` for the second and so on.
    configurations:
      00-keyboard-1:
        id: 00-keyboard-1
        name: "⌨ Keyboard 1"
        kind: !Keyboard
          up: ArrowUp
          down: ArrowDown
          left: ArrowLeft
          right: ArrowRight
          select: KeyQ
          start: KeyW
          b: KeyA
          a: KeyS
      00-keyboard-2:
        id: 00-keyboard-2
        name: "⌨ Keyboard 2"
        kind: !Keyboard
          up: KeyW
          down: KeyS
          left: KeyA
          right: KeyD
          select: KeyU
          start: KeyI
          b: KeyJ
          a: KeyK
      01-gamepad-0:
        id: 01-gamepad-0
        name: "🎮 Gamepad"
        kind: !Gamepad
          up: DPadUp
          down: DPadDown
          left: DPadLeft
          right: DPadRight
          select: Back
          start: Start
          b: West
          a: South
    # The default mapping for newly connected gamepads. For more gamepad button mappings see https://github.com/tedsteen/nes-bundler/blob/master/src/input/buttons.rs#L8.
    default_gamepad_mapping:
      up: DPadUp
      down: DPadDown
      left: DPadLeft
      right: DPadRight
      select: Back
      start: Start
      b: West
      a: South
